# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2dbc60672662fefa294387fd74149f3798c4301f0c83cb957728671ebcff70a0a7dd689ee38e8433956c785509b5a9e212d99be0a139a93e1e8dd66bb536f9b

test:
  secret_key_base: 4f7efe423cdb1ddbcd1d2097bfab68aedefcc8aae1b97e1d74673a585a8f3b6c43d713b9b5e71e123aaaeaea5d6ca3ab1f3f433fe898b6a332409e065b9c5134

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
